# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 71
BUILD_TS = "2026-06-29T19:27:36Z"
GIT_COMMIT = "a1eb259"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
