# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 69
BUILD_TS = "2026-06-29T19:18:05Z"
GIT_COMMIT = "28d133b"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
