# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 115
BUILD_TS = "2026-07-09T19:03:52Z"
GIT_COMMIT = "6af9770"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
