# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 203
BUILD_TS = "2026-09-06T02:34:29Z"
GIT_COMMIT = "7030f7e"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
