# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 47
BUILD_TS = "2026-06-28T01:28:20Z"
GIT_COMMIT = "407e486"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
