# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 150
BUILD_TS = "2026-08-09T01:21:45Z"
GIT_COMMIT = "17344b648a10d9af2d1cbd3505a96970cd53a5f1"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
