[Unit]
OnFailure=gptadmin-failover-controller.service

[Service]
ExecStop=/usr/local/sbin/gptadmin-primary-stop $MAINPID
ExecStopPost=/bin/systemctl --no-block start gptadmin-failover-controller.service
ExecStartPost=/bin/systemctl --no-block start gptadmin-failover-controller.service
TimeoutStopSec=15
