# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 36
BUILD_TS = "2026-05-31T13:28:12Z"
GIT_COMMIT = "f050767"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
