# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 35
BUILD_TS = "2026-05-31T13:24:03Z"
GIT_COMMIT = "75c1e6a"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
