# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 40
BUILD_TS = "2026-06-01T03:58:39Z"
GIT_COMMIT = "f83d820"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
