# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 103
BUILD_TS = "2026-07-03T01:02:22Z"
GIT_COMMIT = "89fb29c"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
