#!/usr/bin/env python3
"""GPTAdmin self-hosted hub failover watchdog.

Runs on a fallback node. It intentionally does not require an external
coordinator. Fencing is deterministic: each fallback node has a configured rank;
rank 1 promotes after fail_count_base failures, rank 2 after 2*base, etc.
Before promotion it performs a second short check against the public hub URL.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

DEFAULT_CONFIG = "/etc/gptadmin/failover_config.json"
DEFAULT_STATE = "/etc/gptadmin/failover_state.json"
DEFAULT_RUNTIME = "/var/lib/gptadmin/failover_watchdog_state.json"
DEFAULT_FRPC = "/etc/gptadmin/frpc-failover.toml"
DEFAULT_SERVICE = "gptadmin-failover-frpc.service"


def load_json(path: str, default: Any) -> Any:
    try:
        return json.loads(Path(path).read_text())
    except FileNotFoundError:
        return default
    except json.JSONDecodeError as exc:
        raise SystemExit(f"invalid JSON {path}: {exc}") from exc


def save_json(path: str, data: Any, mode: int = 0o600) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
    os.chmod(tmp, mode)
    tmp.replace(p)


def http_ok(url: str, timeout: float) -> bool:
    if not url:
        return False
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "gptadmin-failover-watchdog/1"})
        with urllib.request.urlopen(req, timeout=timeout) as r:  # noqa: S310 - admin configured URL
            return 200 <= int(getattr(r, "status", 0)) < 500
    except (OSError, urllib.error.URLError, urllib.error.HTTPError):
        return False


def choose_node(cfg: dict[str, Any], node_id: str) -> dict[str, Any]:
    for node in cfg.get("nodes") or []:
        if node.get("server_id") == node_id:
            return node
    raise SystemExit(f"node_id {node_id!r} is not configured in failover nodes")


def threshold(cfg: dict[str, Any], node: dict[str, Any]) -> int:
    base = int(cfg.get("fail_count_base") or 3)
    rank = int(node.get("rank") or 1)
    if cfg.get("deterministic_rank_backoff", True):
        return max(1, base * max(1, rank))
    return max(1, base)


def state_public_url(bundle: dict[str, Any], cfg: dict[str, Any]) -> str:
    return str(
        cfg.get("primary_public_url")
        or bundle.get("hub_public_url")
        or ((bundle.get("tunnel") or {}).get("frp") or {}).get("public_url")
        or ""
    ).rstrip("/")


def build_frpc_config(bundle: dict[str, Any], local_port: int, node_id: str) -> str:
    frp = ((bundle.get("tunnel") or {}).get("frp") or {})
    token = frp.get("token") or os.environ.get("FRP_TOKEN") or ""
    subdomain = frp.get("subdomain") or ""
    domain = frp.get("domain") or ""
    endpoints = frp.get("endpoints") or []
    if isinstance(endpoints, str):
        endpoints = [x.strip() for x in endpoints.split(",") if x.strip()]
    if not endpoints:
        addr = frp.get("server_addr") or ""
        port = frp.get("server_port") or "7000"
        if addr:
            endpoints = [f"primary={addr}:{port}"]
    if not token or not subdomain or not endpoints:
        raise SystemExit("failover state does not contain enough FRP data: token/subdomain/endpoints required")
    parts: list[str] = [
        "# generated by gptadmin_failover_watchdog.py",
        f"# node_id = {node_id}",
    ]
    for idx, endpoint in enumerate(endpoints):
        label = f"e{idx+1}"
        hostport = str(endpoint)
        if "=" in hostport:
            label, hostport = hostport.split("=", 1)
        host, _, port = hostport.partition(":")
        port = port or str(frp.get("server_port") or "7000")
        suffix = "" if idx == 0 else f"-{label}"
        parts += [
            "",
            f"serverAddr = {json.dumps(host)}",
            f"serverPort = {int(port)}",
            "",
            "[auth]",
            f"token = {json.dumps(token)}",
            "",
            "[transport.tls]",
            "enable = true",
        ]
        if domain:
            parts.append(f"serverName = {json.dumps(domain)}")
        parts += [
            "",
            "[[proxies]]",
            f"name = {json.dumps('gptadmin-failover-' + subdomain + suffix)}",
            'type = "http"',
            'localIP = "127.0.0.1"',
            f"localPort = {int(local_port)}",
            f"subdomain = {json.dumps(subdomain)}",
        ]
    return "\n".join(parts) + "\n"


def run(cmd: list[str], dry_run: bool) -> None:
    if dry_run:
        print("DRY-RUN", " ".join(cmd))
        return
    subprocess.run(cmd, check=True)


def promote(args: argparse.Namespace, cfg: dict[str, Any], bundle: dict[str, Any], node: dict[str, Any], dry_run: bool) -> None:
    local_port = int(node.get("local_hub_port") or ((bundle.get("tunnel") or {}).get("frp") or {}).get("local_port") or 9001)
    if args.hub_service and args.hub_service != "none":
        run(["systemctl", "start", args.hub_service], dry_run)
    text = build_frpc_config(bundle, local_port, args.node_id)
    if dry_run:
        print("DRY-RUN write", args.frpc_config)
        print(text)
    else:
        p = Path(args.frpc_config)
        p.parent.mkdir(parents=True, exist_ok=True)
        tmp = p.with_suffix(p.suffix + ".tmp")
        tmp.write_text(text)
        os.chmod(tmp, 0o600)
        tmp.replace(p)
    if args.frpc_service and args.frpc_service != "none":
        run(["systemctl", "restart", args.frpc_service], dry_run)
    else:
        if dry_run:
            print("DRY-RUN", args.frpc_bin, "-c", args.frpc_config)
        else:
            subprocess.Popen([args.frpc_bin, "-c", args.frpc_config], start_new_session=True)


def check_once(args: argparse.Namespace) -> int:
    cfg = load_json(args.config, {})
    bundle = load_json(args.state, {})
    node = choose_node(cfg, args.node_id)
    runtime = load_json(args.runtime_state, {})
    runtime.setdefault("node_id", args.node_id)
    runtime.setdefault("fail_count", 0)
    runtime.setdefault("last_promotion_at", 0)
    runtime["last_check_at"] = time.time()

    if not cfg.get("enabled") or not node.get("enabled", True):
        runtime["last_decision"] = "disabled"
        save_json(args.runtime_state, runtime)
        print(json.dumps({"ok": True, "decision": "disabled", "node_id": args.node_id}, sort_keys=True))
        return 0

    timeout = float(cfg.get("public_confirm_timeout_sec") or 3)
    health_url = str(cfg.get("primary_health_url") or "")
    public_url = state_public_url(bundle, cfg)
    primary_ok = http_ok(health_url, timeout)
    if primary_ok:
        runtime["fail_count"] = 0
        runtime["last_decision"] = "primary_ok"
        save_json(args.runtime_state, runtime)
        print(json.dumps({"ok": True, "decision": "primary_ok", "node_id": args.node_id, "health_url": health_url}, sort_keys=True))
        return 0

    runtime["fail_count"] = int(runtime.get("fail_count") or 0) + 1
    need = threshold(cfg, node)
    if int(runtime["fail_count"]) < need:
        runtime["last_decision"] = "waiting_rank_threshold"
        save_json(args.runtime_state, runtime)
        print(json.dumps({"ok": True, "decision": "waiting_rank_threshold", "fail_count": runtime["fail_count"], "threshold": need, "node_id": args.node_id}, sort_keys=True))
        return 0

    public_health = public_url + "/version" if public_url else ""
    if http_ok(public_health, timeout):
        runtime["fail_count"] = 0
        runtime["last_decision"] = "public_confirm_ok"
        save_json(args.runtime_state, runtime)
        print(json.dumps({"ok": True, "decision": "public_confirm_ok", "public_url": public_health, "node_id": args.node_id}, sort_keys=True))
        return 0

    cooldown = int(cfg.get("promotion_cooldown_sec") or 300)
    now = time.time()
    if now - float(runtime.get("last_promotion_at") or 0) < cooldown:
        runtime["last_decision"] = "cooldown"
        save_json(args.runtime_state, runtime)
        print(json.dumps({"ok": True, "decision": "cooldown", "node_id": args.node_id}, sort_keys=True))
        return 0

    runtime["last_decision"] = "promote"
    runtime["last_promotion_at"] = now
    save_json(args.runtime_state, runtime)
    promote(args, cfg, bundle, node, args.dry_run)
    print(json.dumps({"ok": True, "decision": "promote", "node_id": args.node_id, "threshold": need, "public_confirm": public_health, "dry_run": args.dry_run}, sort_keys=True))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=os.environ.get("GPTADMIN_FAILOVER_CONFIG_FILE", DEFAULT_CONFIG))
    ap.add_argument("--state", default=os.environ.get("GPTADMIN_FAILOVER_STATE_FILE", DEFAULT_STATE))
    ap.add_argument("--runtime-state", default=DEFAULT_RUNTIME)
    ap.add_argument("--node-id", default=os.environ.get("GPTADMIN_FAILOVER_NODE_ID", ""), required=os.environ.get("GPTADMIN_FAILOVER_NODE_ID", "") == "")
    ap.add_argument("--hub-service", default=os.environ.get("GPTADMIN_FAILOVER_HUB_SERVICE", "gptadmin-hub.service"))
    ap.add_argument("--frpc-service", default=os.environ.get("GPTADMIN_FAILOVER_FRPC_SERVICE", DEFAULT_SERVICE))
    ap.add_argument("--frpc-config", default=os.environ.get("GPTADMIN_FAILOVER_FRPC_CONFIG", DEFAULT_FRPC))
    ap.add_argument("--frpc-bin", default=os.environ.get("GPTADMIN_FAILOVER_FRPC_BIN", "/opt/gptadmin/bin/frpc"))
    ap.add_argument("--check-once", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    if not args.check_once:
        raise SystemExit("only --check-once is supported; run from systemd timer")
    return check_once(args)


if __name__ == "__main__":
    raise SystemExit(main())
