'use client';
import { useEffect, useState } from 'react';
import { listComputers } from '@/lib/computer-api';
import type { Computer, FileEntry } from '@/lib/types';
export function FilesApp() {
  const [computers, setComputers] = useState<Computer[]>([]), [path, setPath] = useState('/'), [entries, setEntries] = useState<FileEntry[]>([]), [message, setMessage] = useState('Choose a computer to browse.'), [query, setQuery] = useState(''), [search, setSearch] = useState<string>('');
  const [computerId, setComputerId] = useState('');
  const computer = computers.find(item => item.id === computerId);
  useEffect(() => { void listComputers().then(result => setComputers((result.data ?? []).filter(item => item.capabilities.includes('files') && item.capabilities.includes('terminal')))); }, []);
  async function browse(nextPath = path) { if (!computerId) return; setMessage('Loading…'); const response = await fetch(`/api/computer/files?operation=files.list&computer=${encodeURIComponent(computerId)}&path=${encodeURIComponent(nextPath)}`), payload = await response.json(); if (!response.ok || !Array.isArray(payload.data?.entries)) { setEntries([]); setMessage(payload.error || payload.data?.detail || 'Could not load files.'); return; } setPath(payload.data.path || nextPath); setEntries(payload.data.entries); setMessage(`${payload.data.entries.length} real entries from ${computer?.name ?? 'the selected computer'}.`); }
  function changeComputer(id: string) { setComputerId(id); setEntries([]); setPath('/'); setMessage('Computer changed. Open its workspace.'); }
  async function searchMesh() { const response = await fetch('/api/grepmesh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query }) }); const body = await response.json(); setSearch(response.ok ? JSON.stringify(body.data, null, 2) : body.error || 'Search failed'); }
  return <section className="h-full overflow-auto bg-slate-950/60 p-5 text-slate-100"><h2 className="text-lg font-semibold">Files</h2><p className="mt-1 text-sm text-slate-400">Browse a computer workspace. Search uses GrepMesh across enrolled hosts.</p><div className="mt-4 flex gap-2"><select aria-label="Files computer" value={computerId} onChange={event => changeComputer(event.target.value)} className="rounded bg-slate-800 px-3 py-2 text-sm"><option value="">Choose computer…</option>{computers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={() => void browse('/')} disabled={!computerId} className="rounded bg-violet-500 px-3 py-2 text-sm font-medium text-white disabled:opacity-40">Open workspace</button></div><div className="mt-3 flex gap-2"><input aria-label="GrepMesh search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search files with GrepMesh" className="min-w-0 flex-1 rounded bg-slate-800 px-3 py-2 text-sm"/><button onClick={() => void searchMesh()} disabled={!query.trim()} className="rounded bg-slate-700 px-3 py-2 text-sm disabled:opacity-40">Search</button></div>{search && <pre className="mt-2 max-h-40 overflow-auto rounded bg-black/30 p-2 text-xs text-slate-300">{search}</pre>}<p className="mt-3 text-xs text-slate-400">{message}</p><p className="mt-2 font-mono text-xs text-slate-300">{path}</p><div className="mt-3 grid gap-1">{path !== '/' && <button onClick={() => void browse(path.split('/').slice(0, -1).join('/') || '/')} className="rounded p-2 text-left hover:bg-white/10">↩ ..</button>}{entries.map(entry => <button key={entry.path} onClick={() => entry.type === 'directory' && void browse(entry.path)} className="rounded border border-white/10 bg-white/5 p-3 text-left hover:bg-white/10"><span>{entry.type === 'directory' ? '📁' : '📄'} {entry.name}</span><span className="ml-3 text-xs text-slate-400">{entry.type}{entry.size != null ? ` · ${entry.size} B` : ''}</span></button>)}</div></section>;
}
