# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 121
BUILD_TS = "2026-07-11T12:27:22Z"
GIT_COMMIT = "73a227e"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
