# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 120
BUILD_TS = "2026-07-10T20:33:35Z"
GIT_COMMIT = "c8a6744"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
