# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 120
BUILD_TS = "2026-07-10T21:54:43Z"
GIT_COMMIT = "0043334"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
