#!/usr/bin/env bash
# GPTAdmin target-based builder.
# Default target is `all` for backward compatibility.

set -Eeuo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

export PS4='+ [${EPOCHREALTIME}] ${BASH_SOURCE##*/}:${LINENO}: '
set -x
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export PYTHONUTF8=1

ART_DIR="build"
CACHE_DIR=".buildcache"
VERSION_FILE="VERSION"
LOG="$ART_DIR/build.log"
SHELLMCP_RT_LOG="$ART_DIR/shellmcp_runtime.log"
HUB_RT_LOG="$ART_DIR/hub_runtime.log"
FORCE="${FORCE:-0}"
CLEAN="${CLEAN:-0}"
REBUILD_ON_REQ_CHANGE="${REBUILD_ON_REQ_CHANGE:-0}"
SKIP_TESTS="${SKIP_TESTS:-0}"

usage() {
  cat <<'EOF'
Usage: tools/build.sh [target...]

Targets:
  all        Build Linux hub+shellmcp, CLI, source payloads, platform bundles,
             component tarballs, Windows/Android shellmcp packages, and smoke-test Linux bins.
  cli        Package GPTAdmin CLI only: build/gptadmin-cli.tar.gz
  hub        Build/package GPTAdmin hub: build/gptadmin-hub.tar.gz
  shellmcp   Build/package Linux ShellMCP: build/gptadmin-shellmcp.tar.gz
  platform   Package install convenience bundles: build/gptadmin-<os>-<arch>.tar.gz
  windows    Cross-build Windows ShellMCP and public/gptadmin-win.zip
  android    Cross-build Android/Termux ShellMCP and build/gptadmin-android-arm64.tar.gz
  smoke      Smoke-test existing Linux hub+shellmcp binaries
  clean      Remove build/ and .buildcache before selected targets
  help       Show this help

Env:
  FORCE=1 CLEAN=1 SKIP_TESTS=1 REBUILD_ON_REQ_CHANGE=1
  GPTADMIN_HUB_DARWIN_ARM64=/path/gptadmin_hub GPTADMIN_HUB_DARWIN_AMD64=/path/gptadmin_hub
EOF
}

TARGETS=("${@:-all}")
for t in "${TARGETS[@]}"; do
  case "$t" in
    help|-h|--help) usage; exit 0 ;;
    clean) CLEAN=1 ;;
  esac
done

want() {
  local q="$1" t
  for t in "${TARGETS[@]}"; do
    [[ "$t" == "$q" || "$t" == all ]] && return 0
  done
  return 1
}
want_any() {
  local q
  for q in "$@"; do want "$q" && return 0; done
  return 1
}

if [[ "$CLEAN" == "1" ]]; then
  rm -rf "$ART_DIR" "$CACHE_DIR"
fi
mkdir -p "$ART_DIR/cli" "$CACHE_DIR"
: > "$LOG"
exec > >(tee -a "$LOG") 2>&1

SHELLMCP_PID=""
HUB_PID=""
cleanup() {
  set +e
  echo "== cleanup ==" | tee -a "$LOG"
  [[ -n "${SHELLMCP_PID:-}" ]] && kill "$SHELLMCP_PID" 2>/dev/null || true
  [[ -n "${HUB_PID:-}" ]] && kill "$HUB_PID" 2>/dev/null || true
}
trap cleanup EXIT
err_report() {
  local exit_code=$?
  local cmd="${BASH_COMMAND:-unknown}"
  echo
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "BUILD FAILED (exit=$exit_code)"
  echo "Last command: $cmd"
  echo "File: ${BASH_SOURCE[1]:-?}  Line: ${BASH_LINENO[0]:-?}  Func: ${FUNCNAME[1]:-main}"
  echo "---- tail of $LOG ----------------------------------------------------"
  tail -n 200 "$LOG" || true
  echo "---------------------------------------------------------------------"
  [[ -f "$SHELLMCP_RT_LOG" ]] && { echo "--- shellmcp_runtime.log (tail) ---"; tail -n 120 "$SHELLMCP_RT_LOG"; }
  [[ -f "$HUB_RT_LOG" ]] && { echo "--- hub_runtime.log (tail) ---"; tail -n 120 "$HUB_RT_LOG"; }
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  exit "$exit_code"
}
trap err_report ERR

step(){ echo; echo "===== $* ====="; }
need(){ command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing command: $1"; exit 127; }; }

step "Check tooling"
need python3; need tar; need grep; need sed; need awk; need sha256sum
want_any hub shellmcp all smoke && need curl
want_any windows android && need go
want windows && need zip

build_version() {
  step "Bump build version"
  old_version="0"
  [[ -f "$VERSION_FILE" ]] && old_version="$(tr -dc '0-9' < "$VERSION_FILE" || true)"
  [[ -n "$old_version" ]] || old_version="0"
  BUILD_VERSION="$((old_version + 1))"
  printf '%s\n' "$BUILD_VERSION" > "$VERSION_FILE"
  BUILD_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
  GO_SHELLMCP_LDFLAGS=(-ldflags "-s -w -X github.com/megamen32/gptadmin/go-shellmcp/internal/server.BuildVersion=$BUILD_VERSION -X github.com/megamen32/gptadmin/go-shellmcp/internal/server.GitCommit=$GIT_COMMIT")
  GO_HUB_LDFLAGS=(-ldflags "-s -w -X github.com/megamen32/gptadmin/go-hub/internal/hub.BuildVersion=$BUILD_VERSION -X github.com/megamen32/gptadmin/go-hub/internal/hub.GitCommit=$GIT_COMMIT")
  mkdir -p client
  cat > client/gptadmin_build_info.py <<PYINFO
# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = ${BUILD_VERSION}
BUILD_TS = "${BUILD_TS}"
GIT_COMMIT = "${GIT_COMMIT}"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
PYINFO
  cp client/gptadmin_build_info.py gptadmin_build_info.py
  echo "Build version: $BUILD_VERSION ts=$BUILD_TS git=$GIT_COMMIT"
}

ensure_build_info() {
  if [[ ! -f client/gptadmin_build_info.py || ! -f gptadmin_build_info.py ]]; then
    build_version
  else
    BUILD_VERSION="$(python3 - <<'PY'
import re, pathlib
p=pathlib.Path('client/gptadmin_build_info.py')
m=re.search(r'BUILD_VERSION\s*=\s*(\d+)', p.read_text()) if p.exists() else None
print(m.group(1) if m else '0')
PY
)"
    BUILD_TS="$(python3 - <<'PY'
import re, pathlib
p=pathlib.Path('client/gptadmin_build_info.py')
m=re.search(r'BUILD_TS\s*=\s*"([^"]+)"', p.read_text()) if p.exists() else None
print(m.group(1) if m else 'unknown')
PY
)"
    GIT_COMMIT="$(python3 - <<'PY'
import re, pathlib
p=pathlib.Path('client/gptadmin_build_info.py')
m=re.search(r'GIT_COMMIT\s*=\s*"([^"]+)"', p.read_text()) if p.exists() else None
print(m.group(1) if m else 'unknown')
PY
)"
  fi
}

# Build-info changes affect hub/shellmcp binaries, so any real build bumps once.
if want_any all cli hub shellmcp platform windows android; then
  build_version
else
  ensure_build_info
fi

build_cli() {
  step "Build CLI payload"
  mkdir -p "$ART_DIR/cli"
  cp -f cli.py "$ART_DIR/cli/cli.py"
  cp -f cli.py "$ART_DIR/cli/gptadmin.py"
  chmod 755 "$ART_DIR/cli/gptadmin.py"
  (cd "$ART_DIR" && tar -czf gptadmin-cli.tar.gz.tmp.$$ cli && mv -f gptadmin-cli.tar.gz.tmp.$$ gptadmin-cli.tar.gz)
  echo "built: $ART_DIR/gptadmin-cli.tar.gz"
}

fingerprint() {
  local files=()
  for f in "$@"; do [[ -f "$f" ]] && files+=("$f"); done
  [[ ${#files[@]} -eq 0 ]] && { echo "0"; return; }
  sha256sum "${files[@]}" 2>/dev/null | sort -k2 | sha256sum | awk '{print $1}'
}
changed() {
  local cache="$1" newfp="$2" oldfp=""
  [[ -f "$cache" ]] && oldfp="$(cat "$cache" 2>/dev/null || true)"
  [[ "$newfp" != "$oldfp" ]]
}
save_fp() { echo "$2" > "$1"; }

# ShellMCP is now Go-only (go-shellmcp). SHELLMCP_DIST points at the cross-built
# linux/amd64 binary built by build_go_shellmcp_cross_platforms.
SHELLMCP_DIST="$ART_DIR/go-shellmcp/linux_amd64/shellmcp-go"
HUB_DIST="$ART_DIR/gptadmin_hub/dist/gptadmin_hub"

build_hub_linux() {
  step "Go build: gptadmin_hub Linux"
  mkdir -p "$ART_DIR/gptadmin_hub/dist"
  pushd go-hub > /dev/null
  export CGO_ENABLED=0
  GOOS=linux GOARCH=amd64 go build "${GO_HUB_LDFLAGS[@]}" -o "../$HUB_DIST" ./cmd/gptadmin-hub
  popd > /dev/null
  chmod 755 "$HUB_DIST"
}

# Cross-build gptadmin_hub for every platform we ship an install bundle for
# (linux/{amd64,arm64}, darwin/{amd64,arm64}). CGO is disabled, so this is pure
# Go and needs no C cross-toolchain on the amd64 build host. Mirrors
# build_go_shellmcp_cross_platforms. Without this, the linux-arm64 (and the
# darwin) platform archives were skipped because no hub binary existed for
# those arches — so arm64 hosts (e.g. Orange Pi) fell back to the all-in-one
# bundle shipping an amd64 hub that cannot run. See CLAUDE.md "Gotchas".
build_hub_cross_platforms() {
  step "Cross-build Go hub platform binaries"
  pushd go-hub > /dev/null
  export CGO_ENABLED=0
  for pair in linux_amd64 linux_arm64 darwin_amd64 darwin_arm64; do
    local goos="${pair%%_*}" goarch="${pair##*_}"
    mkdir -p "../$ART_DIR/gptadmin_hub/$pair"
    GOOS=$goos GOARCH=$goarch go build "${GO_HUB_LDFLAGS[@]}" \
      -o "../$ART_DIR/gptadmin_hub/$pair/gptadmin_hub" ./cmd/gptadmin-hub
    echo "hub cross-build: $pair/gptadmin_hub"
  done
  popd > /dev/null
}

normalize_arch() {
  case "${1,,}" in x86_64|amd64) echo amd64 ;; arm64|aarch64) echo arm64 ;; *) echo "${1,,}" ;; esac
}
copy_hub_platform_binary() {
  local src="$1" tag="$2" exe_name="${3:-gptadmin_hub}"
  [[ -n "$src" && -x "$src" ]] || return 0
  mkdir -p "$ART_DIR/gptadmin_hub/$tag"
  local dst="$ART_DIR/gptadmin_hub/$tag/$exe_name"
  # Cross-build already places the binary in its destination; copying a file
  # onto itself makes `cp` fail ("один и тот же файл") under errexit. Skip.
  if [[ "$src" -ef "$dst" ]]; then
    echo "hub platform binary: $tag/$exe_name (already in place)"
    return 0
  fi
  cp -f "$src" "$dst"
  chmod 755 "$dst"
  echo "hub platform binary: $tag/$exe_name <= $src"
}
package_hub_platform_binaries() {
  step "Package platform hub binaries"
  # Prefer the cross-built binaries (always present after build_hub_cross_platforms).
  local tag
  for tag in linux_amd64 linux_arm64 darwin_amd64 darwin_arm64; do
    copy_hub_platform_binary "$ART_DIR/gptadmin_hub/$tag/gptadmin_hub" "$tag" gptadmin_hub
  done
  # Legacy fallbacks (env vars / prebuilt dir) — honored only if the
  # cross-build was skipped or a tag is still missing.
  [[ -x "$HUB_DIST" ]] && copy_hub_platform_binary "$HUB_DIST" "linux_$(normalize_arch "$(uname -m)")" "gptadmin_hub"
  copy_hub_platform_binary "${GPTADMIN_HUB_DARWIN_ARM64:-}" darwin_arm64 gptadmin_hub
  copy_hub_platform_binary "${GPTADMIN_HUB_DARWIN_AMD64:-}" darwin_amd64 gptadmin_hub
  copy_hub_platform_binary "${GPTADMIN_HUB_MACOS_ARM64:-}" darwin_arm64 gptadmin_hub
  copy_hub_platform_binary "${GPTADMIN_HUB_MACOS_AMD64:-}" darwin_amd64 gptadmin_hub
  copy_hub_platform_binary prebuilt/gptadmin_hub/darwin_arm64/gptadmin_hub darwin_arm64 gptadmin_hub
  copy_hub_platform_binary prebuilt/gptadmin_hub/darwin_amd64/gptadmin_hub darwin_amd64 gptadmin_hub
}

copy_support_payloads() {
  step "Copy generic stdio MCP agents"
  rm -rf "$ART_DIR/agents"
  mkdir -p "$ART_DIR/agents"
  cp -a agents/generic_stdio_mcp_relay "$ART_DIR/agents/"

  step "Copy source payloads"
  rm -rf "$ART_DIR/hub_source" "$ART_DIR/client"
  mkdir -p "$ART_DIR/hub_source" "$ART_DIR/client"
  cp -a go-hub "$ART_DIR/hub_source/go-hub"
  find "$ART_DIR/hub_source/go-hub" -name '*.bak.*' -delete
  cp -a client/. "$ART_DIR/client/"
  find "$ART_DIR/hub_source" "$ART_DIR/client" \( -name '__pycache__' -o -name '*.pyc' -o -name '*.bak*' \) -print0 | xargs -0 -r rm -rf
}

archive_component_cli() { build_cli; }
archive_component_hub() {
  step "Archive: gptadmin-hub.tar.gz"
  (cd "$ART_DIR" && tar -czf gptadmin-hub.tar.gz.tmp.$$ gptadmin_hub hub_source cli && mv -f gptadmin-hub.tar.gz.tmp.$$ gptadmin-hub.tar.gz)
  echo "built: $ART_DIR/gptadmin-hub.tar.gz"
}
archive_component_shellmcp() {
  step "Archive: gptadmin-shellmcp.tar.gz"
  build_go_shellmcp_cross_platforms
  (cd "$ART_DIR" && tar -czf gptadmin-shellmcp.tar.gz.tmp.$$ shellmcp go-shellmcp cli agents client && mv -f gptadmin-shellmcp.tar.gz.tmp.$$ gptadmin-shellmcp.tar.gz)
  sha256sum "$ART_DIR/gptadmin-shellmcp.tar.gz" > "$ART_DIR/gptadmin-shellmcp.sha256"
  python3 - <<PY
import json, pathlib
sha = pathlib.Path('$ART_DIR/gptadmin-shellmcp.sha256').read_text().split()[0]
pathlib.Path('$ART_DIR/gptadmin-shellmcp.json').write_text(json.dumps({
  'component': 'shellmcp', 'build_version': int('$BUILD_VERSION'), 'build_ts': '$BUILD_TS',
  'git_commit': '$GIT_COMMIT', 'platform': 'linux', 'arch': 'x86_64',
  'artifact_type': 'binary-runtime+source',
  'runtime_payload': ['go-shellmcp/linux_amd64/shellmcp-go', 'cli', 'agents/generic_stdio_mcp_relay', 'client'],
  'source_payload': ['client/gptadmin_security.py', 'client/gptadmin_build_info.py'],
  'sha256': sha, 'url': '/gptadmin-shellmcp.tar.gz'
}, ensure_ascii=False, indent=2) + '\n')
PY
  echo "built: $ART_DIR/gptadmin-shellmcp.tar.gz"
}
archive_all() {
  step "Archive: gptadmin.tar.gz"
  (cd "$ART_DIR" && tar -czf gptadmin.tar.gz.tmp.$$ shellmcp gptadmin_hub cli agents hub_source client && mv -f gptadmin.tar.gz.tmp.$$ gptadmin.tar.gz)
  echo "built: $ART_DIR/gptadmin.tar.gz"
}

make_platform_archive() {
  local platform="$1"
  local arch="$2"
  local hub_tag="$3"
  local out="gptadmin-${platform}-${arch}.tar.gz"
  local tmp
  tmp="$(mktemp -d)"
  mkdir -p "$tmp/gptadmin_hub"
  if [[ -d "$ART_DIR/gptadmin_hub/$hub_tag" ]]; then
    mkdir -p "$tmp/gptadmin_hub/$hub_tag"
    cp -a "$ART_DIR/gptadmin_hub/$hub_tag/." "$tmp/gptadmin_hub/$hub_tag/"
  else
    echo "WARN: skip $out: missing $ART_DIR/gptadmin_hub/$hub_tag"
    rm -rf "$tmp"; return 0
  fi
  for d in cli agents hub_source client; do [[ -d "$ART_DIR/$d" ]] && cp -a "$ART_DIR/$d" "$tmp/"; done
  if [[ -d "$ART_DIR/go-shellmcp/${platform}_${arch}" ]]; then
    mkdir -p "$tmp/go-shellmcp/${platform}_${arch}" "$tmp/shellmcp/${platform}_${arch}"
    cp -a "$ART_DIR/go-shellmcp/${platform}_${arch}/." "$tmp/go-shellmcp/${platform}_${arch}/"
    cp -a "$ART_DIR/go-shellmcp/${platform}_${arch}/." "$tmp/shellmcp/${platform}_${arch}/"
  fi
  if [[ "$platform" == linux && -d "$ART_DIR/shellmcp" ]]; then cp -a "$ART_DIR/shellmcp" "$tmp/"; fi
  tar -C "$tmp" -czf "$ART_DIR/$out.tmp.$$" .
  mv -f "$ART_DIR/$out.tmp.$$" "$ART_DIR/$out"
  rm -rf "$tmp"
  echo "built: $ART_DIR/$out"
}
archive_platforms() {
  step "Archive: platform-specific tarballs"
  make_platform_archive linux amd64 linux_amd64
  make_platform_archive linux arm64 linux_arm64
  make_platform_archive darwin arm64 darwin_arm64
  make_platform_archive darwin amd64 darwin_amd64
}

build_go_shellmcp_cross_platforms() {
  step "Cross-build Go ShellMCP platform binaries"
  mkdir -p \
    "$ART_DIR/go-shellmcp/linux_amd64" \
    "$ART_DIR/go-shellmcp/linux_arm64" \
    "$ART_DIR/go-shellmcp/darwin_amd64" \
    "$ART_DIR/go-shellmcp/darwin_arm64"
  pushd go-shellmcp > /dev/null
  export CGO_ENABLED=0
  GOOS=linux GOARCH=amd64 go build "${GO_SHELLMCP_LDFLAGS[@]}" -o "../$ART_DIR/go-shellmcp/linux_amd64/shellmcp-go" ./cmd/shellmcp-go
  GOOS=linux GOARCH=arm64 go build "${GO_SHELLMCP_LDFLAGS[@]}" -o "../$ART_DIR/go-shellmcp/linux_arm64/shellmcp-go" ./cmd/shellmcp-go
  GOOS=darwin GOARCH=amd64 go build "${GO_SHELLMCP_LDFLAGS[@]}" -o "../$ART_DIR/go-shellmcp/darwin_amd64/shellmcp-go" ./cmd/shellmcp-go
  GOOS=darwin GOARCH=arm64 go build "${GO_SHELLMCP_LDFLAGS[@]}" -o "../$ART_DIR/go-shellmcp/darwin_arm64/shellmcp-go" ./cmd/shellmcp-go
  popd > /dev/null
  chmod 755 "$ART_DIR/go-shellmcp"/*/shellmcp-go
  cp -a "$ART_DIR/go-shellmcp/." "$ART_DIR/shellmcp/"
  find "$ART_DIR/go-shellmcp" "$ART_DIR/shellmcp" -maxdepth 2 -type f -name shellmcp-go -exec file {} \;
}

build_windows_shellmcp() {
  step "Cross-build Windows ShellMCP"
  mkdir -p "$ART_DIR/windows" public
  pushd go-shellmcp >/dev/null
  export CGO_ENABLED=0
  GOOS=windows GOARCH=amd64 go build "${GO_SHELLMCP_LDFLAGS[@]}" -o "../$ART_DIR/windows/shellmcp.exe" ./cmd/shellmcp-go
  popd >/dev/null
  ls -lh "$ART_DIR/windows/shellmcp.exe"
  file "$ART_DIR/windows/shellmcp.exe" || true
  step "Archive: gptadmin-win.zip"
  rm -f "$ART_DIR/gptadmin-win.zip" public/gptadmin-win.zip
  (cd "$ART_DIR/windows" && zip -q -9 "../gptadmin-win.zip" shellmcp.exe)
  cp -f "$ART_DIR/gptadmin-win.zip" public/gptadmin-win.zip
  cp -f deploy/install_win.ps1 public/install_win.ps1
  unzip -l public/gptadmin-win.zip
  sha256sum public/gptadmin-win.zip > public/gptadmin-win.zip.sha256
  echo "built: public/gptadmin-win.zip"
}

build_android_shellmcp() {
  step "Cross-build Android/Termux ShellMCP"
  mkdir -p "$ART_DIR/android-arm64/bin"
  pushd go-shellmcp >/dev/null
  export CGO_ENABLED=0
  GOOS=android GOARCH=arm64 go build "${GO_SHELLMCP_LDFLAGS[@]}" -o "../$ART_DIR/android-arm64/bin/shellmcp" ./cmd/shellmcp-go
  popd >/dev/null
  chmod 755 "$ART_DIR/android-arm64/bin/shellmcp"
  cp -f deploy/install_android.sh "$ART_DIR/android-arm64/install_android.sh"
  chmod 755 "$ART_DIR/android-arm64/install_android.sh"
  cat > "$ART_DIR/android-arm64/README.android.md" <<EOF
# GPTAdmin ShellMCP for Android / Termux

This package contains only the ShellMCP reliable transport for Android.
It is intended to run in Termux in long-poll mode; the GPTAdmin hub stays on your server.

Install:

    curl -fsSL https://became.bezrabotnyi.com/install_android.sh | bash

Optional Shizuku/rish privilege mode:

    # Default is auto. Export rish/rish_shizuku.dex from Shizuku into Termux
    # and restart ShellMCP; explicit root/sudo shell_exec requests will use rish.
    curl -fsSL https://became.bezrabotnyi.com/install_android.sh | bash

Modes:

- auto: normal Termux shell_exec; root/sudo requests use rish when available.
- none: normal Termux shell_exec only.
- shizuku: force explicit root/sudo shell_exec requests through rish.
- shizuku-all: every shell_exec runs through rish.

EOF
  file "$ART_DIR/android-arm64/bin/shellmcp" || true
  (cd "$ART_DIR/android-arm64" && tar -czf "../gptadmin-android-arm64.tar.gz.tmp.$$" bin install_android.sh README.android.md)
  mv -f "$ART_DIR/gptadmin-android-arm64.tar.gz.tmp.$$" "$ART_DIR/gptadmin-android-arm64.tar.gz"
  sha256sum "$ART_DIR/gptadmin-android-arm64.tar.gz" > "$ART_DIR/gptadmin-android-arm64.sha256"
  printf '%s\n' "$BUILD_VERSION" > "$ART_DIR/gptadmin-android-arm64.version"
  echo "built: $ART_DIR/gptadmin-android-arm64.tar.gz"
}

wait_for_http() {
  local url="$1" timeout="${2:-20}"; shift 2 || true
  local attempt
  for ((attempt=1; attempt<=timeout; attempt++)); do
    if curl -sS "$url" "$@" -o /dev/null; then echo "HTTP OK: $url (attempt $attempt/$timeout)"; return 0; fi
    sleep 1
  done
  echo "Timeout waiting for $url"; return 1
}
wait_for_listen_port() {
  local port="$1" timeout="${2:-20}" line attempt
  for ((attempt=1; attempt<=timeout; attempt++)); do
    line="$(ss -ltn "( sport = :$port )" 2>/dev/null | sed -n '2p' || true)"
    [[ -n "$line" ]] && { echo "LISTEN OK: :$port (attempt $attempt/$timeout)"; return 0; }
    sleep 1
  done
  echo "Timeout waiting for port :$port to listen"; return 1
}
is_port_busy() {
  local port="$1" line out
  if command -v ss >/dev/null 2>&1; then line="$(ss -ltn "( sport = :$port )" 2>/dev/null | sed -n '2p' || true)"; [[ -n "$line" ]];
  elif command -v lsof >/dev/null 2>&1; then out="$(lsof -nP -iTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"; [[ -n "$out" ]];
  else return 1; fi
}
pick_port_plus1() {
  local base="$1" port
  for ((port=base; port<base+50; port++)); do if ! is_port_busy "$port"; then echo "$port"; return 0; fi; done
  echo "ERROR: no free port in range $base..$((base+49))" >&2; exit 1
}
smoke_linux() {
  if [[ "$SKIP_TESTS" == 1 ]]; then echo "Skip smoke tests (SKIP_TESTS=1)"; return 0; fi
  [[ -x "$SHELLMCP_DIST" ]] || { echo "Missing $SHELLMCP_DIST"; exit 1; }
  [[ -x "$HUB_DIST" ]] || { echo "Missing $HUB_DIST"; exit 1; }
  step "Smoke test: shellmcp"
  : > "$SHELLMCP_RT_LOG"
  SHELLMCP_PORT="$(pick_port_plus1 25900)"
  SHELLMCP_TOKEN=testtoken HUB_URL='' PORT="$SHELLMCP_PORT" SHELL_PORT="$SHELLMCP_PORT" SHELLMCP_PORT="$SHELLMCP_PORT" "$SHELLMCP_DIST" >"$SHELLMCP_RT_LOG" 2>&1 &
  SHELLMCP_PID=$!
  wait_for_http "http://127.0.0.1:${SHELLMCP_PORT}/version" 25
  curl -sS -f "http://127.0.0.1:${SHELLMCP_PORT}/version" | grep -q build_version
  kill "$SHELLMCP_PID" || true; SHELLMCP_PID=""
  step "Smoke test: gptadmin_hub"
  : > "$HUB_RT_LOG"
  HUB_PORT="$(pick_port_plus1 9001)"
  CTL_TOKEN=ctltest HUB_PORT="$HUB_PORT" "$HUB_DIST" >"$HUB_RT_LOG" 2>&1 &
  HUB_PID=$!
  wait_for_listen_port "$HUB_PORT" 25
  wait_for_http "http://127.0.0.1:${HUB_PORT}/version" 10
  curl -sS -f "http://127.0.0.1:${HUB_PORT}/version" | grep -q build_version
  curl -sS -f "http://127.0.0.1:${HUB_PORT}/servers" -H "Authorization: Bearer ctltest" >/dev/null
  kill "$HUB_PID" || true; HUB_PID=""
}

# Dependency expansion.
if want all; then
  build_cli
  build_hub_linux
  build_hub_cross_platforms
  package_hub_platform_binaries
  copy_support_payloads
  archive_component_cli
  archive_component_hub
  archive_component_shellmcp
  archive_all
  archive_platforms
  build_windows_shellmcp
  build_android_shellmcp
  smoke_linux
else
  want cli && build_cli
  if want shellmcp; then build_cli; copy_support_payloads; archive_component_shellmcp; fi
  if want hub; then build_cli; build_hub_linux; build_hub_cross_platforms; package_hub_platform_binaries; copy_support_payloads; archive_component_hub; fi
  if want platform; then build_cli; build_hub_cross_platforms; package_hub_platform_binaries; copy_support_payloads; archive_platforms; fi
  want windows && build_windows_shellmcp
  want android && build_android_shellmcp
  want smoke && smoke_linux
fi

step "DONE: Artifacts stored in $ART_DIR"
echo "Targets: ${TARGETS[*]}"
echo "Main log: $LOG"
echo "Runtime logs: $SHELLMCP_RT_LOG, $HUB_RT_LOG"
echo "Cache dir: $CACHE_DIR (delete with CLEAN=1)"
ls -lh "$ART_DIR"/gptadmin*.tar.gz "$ART_DIR"/gptadmin*.zip public/gptadmin-win.zip 2>/dev/null || true
