#!/usr/bin/env bash
# Incremental & robust build with auto --collect-all and logs in build/

set -Eeuo pipefail

# Always run from repo root.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

# ---------- pretty xtrace ----------
export PS4='+ [${EPOCHREALTIME}] ${BASH_SOURCE##*/}:${LINENO}: '
set -x
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export PYTHONUTF8=1

ART_DIR="build"
CACHE_DIR=".buildcache"
VERSION_FILE="VERSION"
LOG="$ART_DIR/build.log"
SHELLMCP_RT_LOG="$ART_DIR/shellmcp_runtime.log"
HUB_RT_LOG="$ART_DIR/hub_runtime.log"

SHELLMCP_PID=""
HUB_PID=""

FORCE="${FORCE:-0}"                    # 1 = force rebuild components regardless of fingerprint
CLEAN="${CLEAN:-0}"                    # 1 = full clean of build/ and cache
REBUILD_ON_REQ_CHANGE="${REBUILD_ON_REQ_CHANGE:-0}"  # 1 = include requirements.txt into fingerprints
SKIP_TESTS="${SKIP_TESTS:-0}"          # 1 = skip smoke tests

# ---------- clean or keep previous build ----------
if [[ "$CLEAN" == "1" ]]; then
  rm -rf "$ART_DIR" "$CACHE_DIR"
fi
mkdir -p "$ART_DIR/cli" "$CACHE_DIR"

# ---------- tee to build/build.log ----------
: > "$LOG"
exec > >(tee -a "$LOG") 2>&1

cleanup() {
  set +e
  echo "== cleanup ==" | tee -a "$LOG"
  [[ -n "$SHELLMCP_PID" ]] && kill "$SHELLMCP_PID" 2>/dev/null || true
  [[ -n "$HUB_PID"   ]] && kill "$HUB_PID"   2>/dev/null || true
}
trap cleanup EXIT

err_report() {
  local exit_code=$?
  local cmd="${BASH_COMMAND:-unknown}"
  echo
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "BUILD FAILED (exit=$exit_code)"
  echo "Last command: $cmd"
  echo "File: ${BASH_SOURCE[1]:-?}  Line: ${BASH_LINENO[0]:-?}  Func: ${FUNCNAME[1]:-main}"
  echo "---- tail of $LOG ----------------------------------------------------"
  tail -n 200 "$LOG" || true
  echo "---------------------------------------------------------------------"
  echo "Runtime logs (if any):"
  [[ -f "$SHELLMCP_RT_LOG" ]] && { echo "--- shellmcp_runtime.log (tail) ---"; tail -n 120 "$SHELLMCP_RT_LOG"; }
  [[ -f "$HUB_RT_LOG"   ]] && { echo "--- hub_runtime.log (tail) ---";   tail -n 120 "$HUB_RT_LOG"; }
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  exit "$exit_code"
}
trap err_report ERR

step(){ echo; echo "===== $* ====="; }
need(){ command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing command: $1"; exit 127; }; }

# ---------- tooling ----------
step "Check tooling"
need curl; need python3; need tar; need grep; need sed; need awk; need sha256sum

step "Bump build version"
old_version="0"
[[ -f "$VERSION_FILE" ]] && old_version="$(tr -dc '0-9' < "$VERSION_FILE" || true)"
[[ -n "$old_version" ]] || old_version="0"
BUILD_VERSION="$((old_version + 1))"
printf '%s\n' "$BUILD_VERSION" > "$VERSION_FILE"
BUILD_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
cat > client/gptadmin_build_info.py <<PYINFO
# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = ${BUILD_VERSION}
BUILD_TS = "${BUILD_TS}"
GIT_COMMIT = "${GIT_COMMIT}"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
PYINFO
cp client/gptadmin_build_info.py gptadmin_build_info.py
echo "Build version: $BUILD_VERSION ts=$BUILD_TS git=$GIT_COMMIT"


# ---------- include CLI ----------
step "Include gptadmin.py"
CLI_SRC="cli.py"
if [[ -f "$CLI_SRC" ]]; then
  rm -f "$ART_DIR/cli/cli.py" "$ART_DIR/cli/gptadmin.py"
  cp "$CLI_SRC" "$ART_DIR/cli/cli.py"
  cp "$CLI_SRC" "$ART_DIR/cli/gptadmin.py"
  chmod 755 "$ART_DIR/cli/gptadmin.py"
else
  echo "WARN: $CLI_SRC not found; continuing without it"
fi

# ---------- venv ----------
step "Create/activate venv"
if [[ ! -d "$ART_DIR/venv" ]]; then
  python3 -V
  python3 -m venv "$ART_DIR/venv"
fi
# shellcheck disable=SC1091
source "$ART_DIR/venv/bin/activate"

step "pip versions"
python -V
pip --version || true

# ---------- install deps (verbose) ----------
step "pip install project deps, pyinstaller"
pip install -vvv --upgrade pip
if [[ -f requirements.txt ]]; then
  pip install -vvv -r requirements.txt pyinstaller
else
  pip install -vvv . pyinstaller
fi

step "Tool versions"
pyinstaller --version || true
pyarmor --version || true

# ---------- incremental helpers ----------
fingerprint() {
  # usage: fingerprint <files...>  -> prints single sha256
  local files=()
  for f in "$@"; do [[ -f "$f" ]] && files+=("$f"); done
  [[ ${#files[@]} -eq 0 ]] && { echo "0"; return; }
  # stable ordering by path
  sha256sum "${files[@]}" 2>/dev/null | sort -k2 | sha256sum | awk '{print $1}'
}

changed() {
  # usage: changed <cache_file> <new_fp>
  local cache="$1"; local newfp="$2"; local oldfp=""
  [[ -f "$cache" ]] && oldfp="$(cat "$cache" 2>/dev/null || true)"
  [[ "$newfp" != "$oldfp" ]]
}

save_fp() { echo "$2" > "$1"; }

# ---------- build collect-all flags from requirements.txt ----------
step "Generate --collect-all flags from requirements.txt"
REQ_FILE="requirements.txt"
COLLECT_FLAGS=()
if [[ -f "$REQ_FILE" ]]; then
  MAP_PKGS=$(python - <<'PY'
import re
names=set()
for raw in open("requirements.txt", encoding="utf-8"):
    line=raw.strip()
    if not line or line.startswith("#"): continue
    line=line.split("#",1)[0].strip()
    line=line.split(";",1)[0].strip()
    m=re.match(r'([A-Za-z0-9_.\-+]+)', line)
    if not m: continue
    name=m.group(1).split("[",1)[0]
    if name in ("-e",".","src"): continue
    if name.startswith(("git+","http://","https://","file:")): continue
    names.add(name)
for n in sorted(names):
    print(n)
PY
)
  while IFS= read -r pkg; do
    [[ -n "$pkg" ]] || continue
    COLLECT_FLAGS+=( --collect-all "$pkg" )
  done <<< "$MAP_PKGS"
else
  echo "WARN: requirements.txt not found; using minimal collect set"
  COLLECT_FLAGS+=( --collect-all fastapi --collect-all starlette --collect-all pydantic --collect-all anyio --collect-all uvicorn )
fi
# common extra
COLLECT_FLAGS+=( --collect-all psutil --collect-all cryptography )
printf 'collect-all flags: %q ' "${COLLECT_FLAGS[@]}"; echo

# ---------- hidden-import autodetect via AST ----------
step "Detect hidden imports from sources"
py_hidden_imports() {
python - "$@" <<'PY'
import ast, sys, pathlib
mods=set()
for p in sys.argv[1:]:
    src=pathlib.Path(p).read_text(encoding='utf-8')
    tree=ast.parse(src, filename=p)
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            for a in n.names:
                mods.add(a.name.split('.')[0])
        elif isinstance(n, ast.ImportFrom):
            if n.module:
                mods.add(n.module.split('.')[0])
mods |= {
    "platform","asyncio","typing","pathlib","logging","json","re","time","datetime",
    "http","socket","subprocess","threading","concurrent","importlib","pkgutil","inspect",
    "uvicorn","fastapi","starlette","pydantic","anyio","sniffio","typing_extensions",
    "requests","httpx","psutil","cryptography"
}
print("\n".join(sorted(mods)))
PY
}
to_pyinstaller_flags() { awk '{print "--hidden-import="$0}' | xargs; }

SHELLMCP_IMPORTS=$(py_hidden_imports client/shellmcp.py client/shellmcp_pure.py client/gptadmin_build_info.py client/gptadmin_security.py)
HUB_IMPORTS=$(py_hidden_imports gptadmin_hub.py gptadmin_build_info.py gptadmin_security.py)
SHELLMCP_HIDDEN_FLAGS=$(echo "$SHELLMCP_IMPORTS" | to_pyinstaller_flags)
HUB_HIDDEN_FLAGS=$(echo "$HUB_IMPORTS" | to_pyinstaller_flags)
[[ -f client/shellmcp_linux.py ]] && SHELLMCP_HIDDEN_FLAGS="$SHELLMCP_HIDDEN_FLAGS --hidden-import=shellmcp_linux"
[[ -f client/shellmcp_win.py   ]] && SHELLMCP_HIDDEN_FLAGS="$SHELLMCP_HIDDEN_FLAGS --hidden-import=shellmcp_win"
[[ -f client/shellmcp_mac.py   ]] && SHELLMCP_HIDDEN_FLAGS="$SHELLMCP_HIDDEN_FLAGS --hidden-import=shellmcp_mac"
echo "SHELLMCP hidden-imports flags: $SHELLMCP_HIDDEN_FLAGS"
echo "HUB   hidden-imports flags: $HUB_HIDDEN_FLAGS"

# ---------- fingerprints ----------
SHELLMCP_SRC=(client/shellmcp.py client/shellmcp_pure.py client/gptadmin_build_info.py client/gptadmin_security.py cli.py)
[[ -f client/shellmcp_linux.py ]] && SHELLMCP_SRC+=(client/shellmcp_linux.py)
[[ -f client/shellmcp_win.py   ]] && SHELLMCP_SRC+=(client/shellmcp_win.py)
[[ -f client/shellmcp_mac.py   ]] && SHELLMCP_SRC+=(client/shellmcp_mac.py)
[[ "$REBUILD_ON_REQ_CHANGE" == "1" && -f requirements.txt ]] && SHELLMCP_SRC+=(requirements.txt)

HUB_SRC=(gptadmin_hub.py gptadmin_build_info.py gptadmin_security.py)
[[ "$REBUILD_ON_REQ_CHANGE" == "1" && -f requirements.txt ]] && HUB_SRC+=(requirements.txt)

FP_SHELLMCP_NEW="$(fingerprint "${SHELLMCP_SRC[@]}")"
FP_HUB_NEW="$(fingerprint "${HUB_SRC[@]}")"
FP_SHELLMCP_FILE="$CACHE_DIR/.fp_shellmcp"
FP_HUB_FILE="$CACHE_DIR/.fp_hub"

SHELLMCP_DIST="$ART_DIR/shellmcp/dist/shellmcp"
HUB_DIST="$ART_DIR/gptadmin_hub/dist/gptadmin_hub"

NEED_BUILD_SHELLMCP="$FORCE"
NEED_BUILD_HUB="$FORCE"

if [[ "$NEED_BUILD_SHELLMCP" == "0" ]]; then
  if [[ ! -x "$SHELLMCP_DIST" ]] || changed "$FP_SHELLMCP_FILE" "$FP_SHELLMCP_NEW"; then
    NEED_BUILD_SHELLMCP=1
  fi
fi
if [[ "$NEED_BUILD_HUB" == "0" ]]; then
  if [[ ! -x "$HUB_DIST" ]] || changed "$FP_HUB_FILE" "$FP_HUB_NEW"; then
    NEED_BUILD_HUB=1
  fi
fi

echo "Fingerprint shellmcp: $FP_SHELLMCP_NEW (changed=$([[ $NEED_BUILD_SHELLMCP == 1 ]] && echo yes || echo no))"
echo "Fingerprint hub   : $FP_HUB_NEW (changed=$([[ $NEED_BUILD_HUB == 1 ]] && echo yes || echo no))"

# ---------- PyInstaller (incremental, no obfuscation) ----------
: "${PYTHONPATH:=}"
export PYTHONPATH="client:$PYTHONPATH"
mkdir -p "$ART_DIR/shellmcp" "$ART_DIR/gptadmin_hub"

if [[ "$NEED_BUILD_SHELLMCP" == "1" ]]; then
  step "PyInstaller: build shellmcp"
  pyinstaller "client/shellmcp.py" \
    --onefile --noconfirm --clean \
    --log-level=DEBUG \
    --specpath "$ART_DIR/shellmcp" \
    "${COLLECT_FLAGS[@]}" \
    $SHELLMCP_HIDDEN_FLAGS \
    --distpath "$ART_DIR/shellmcp/dist" \
    --workpath "$ART_DIR/shellmcp/build"
  save_fp "$FP_SHELLMCP_FILE" "$FP_SHELLMCP_NEW"
else
  echo "Skip PyInstaller shellmcp"
fi

if [[ "$NEED_BUILD_HUB" == "1" ]]; then
  step "PyInstaller: build gptadmin_hub"
  pyinstaller "gptadmin_hub.py" \
    --onefile --noconfirm --clean \
    --log-level=DEBUG \
    --specpath "$ART_DIR/gptadmin_hub" \
    "${COLLECT_FLAGS[@]}" \
    $HUB_HIDDEN_FLAGS \
    --distpath "$ART_DIR/gptadmin_hub/dist" \
    --workpath "$ART_DIR/gptadmin_hub/build"
  save_fp "$FP_HUB_FILE" "$FP_HUB_NEW"
else
  echo "Skip PyInstaller gptadmin_hub"
fi

# ---------- Summarize PyInstaller warnings ----------
step "Summarize PyInstaller warnings"
for f in "$ART_DIR"/shellmcp/build/shellmcp/warn-*.txt "$ART_DIR"/gptadmin_hub/build/gptadmin_hub/warn-*.txt; do
  [[ -f "$f" ]] || continue
  echo "--- $(basename "$f") ---"
  sed -n '1,200p' "$f"
done

# ---------- Copy generic stdio MCP agents ----------
step "Copy generic stdio MCP agents"
rm -rf "$ART_DIR/agents"
mkdir -p "$ART_DIR/agents"
cp -a agents/generic_stdio_mcp_relay "$ART_DIR/agents/"

# ---------- Source payloads for non-Linux installers ----------
step "Copy source payloads for macOS/pure-Python installs"
rm -rf "$ART_DIR/hub_source" "$ART_DIR/client"
mkdir -p "$ART_DIR/hub_source" "$ART_DIR/client"
cp -a gptadmin_hub.py gptadmin_build_info.py gptadmin_security.py "$ART_DIR/hub_source/"
cat > "$ART_DIR/hub_source/requirements-hub.txt" <<'REQ'
fastapi
uvicorn[standard]
httpx
pydantic
cryptography
psutil
requests
REQ
cp -a client/. "$ART_DIR/client/"
find "$ART_DIR/hub_source" "$ART_DIR/client"   \( -name '__pycache__' -o -name '*.pyc' -o -name '*.bak*' \) -print0 | xargs -0 -r rm -rf

# ---------- Archive (include CLI, MCP agents and source payloads) ----------
step "Archive: gptadmin.tar.gz"
# Тарим только существующие папки (на случай первой частичной сборки)
pushd "$ART_DIR" >/dev/null
INCLUDE=()
for d in shellmcp gptadmin_hub cli agents hub_source client; do [[ -d "$d" ]] && INCLUDE+=("$d"); done
tar -czf "gptadmin.tar.gz.tmp.$$" "${INCLUDE[@]}"
mv -f "gptadmin.tar.gz.tmp.$$" gptadmin.tar.gz

# NEW: компонентные архивы (если есть соответствующие папки)
step "Archive: per-component tarballs"
if [[ -d gptadmin_hub ]]; then
  HUB_INCLUDE=(gptadmin_hub)
  [[ -d hub_source ]] && HUB_INCLUDE+=(hub_source)
  [[ -d cli ]] && HUB_INCLUDE+=(cli)
  tar -czf "gptadmin-hub.tar.gz.tmp.$$" "${HUB_INCLUDE[@]}"
mv -f "gptadmin-hub.tar.gz.tmp.$$" gptadmin-hub.tar.gz
  echo "built: $ART_DIR/gptadmin-hub.tar.gz"
else
  echo "WARN: gptadmin_hub dir not found, skip gptadmin-hub.tar.gz"
fi

if [[ -d shellmcp ]]; then
  SHELLMCP_INCLUDE=(shellmcp)
  [[ -d cli ]] && SHELLMCP_INCLUDE+=(cli)
  [[ -d agents ]] && SHELLMCP_INCLUDE+=(agents)
  [[ -d client ]] && SHELLMCP_INCLUDE+=(client)
  tar -czf "gptadmin-shellmcp.tar.gz.tmp.$$" "${SHELLMCP_INCLUDE[@]}"
mv -f "gptadmin-shellmcp.tar.gz.tmp.$$" gptadmin-shellmcp.tar.gz
  sha256sum gptadmin-shellmcp.tar.gz > gptadmin-shellmcp.sha256
  python - <<PY
import json, pathlib
sha = pathlib.Path("gptadmin-shellmcp.sha256").read_text().split()[0]
pathlib.Path("gptadmin-shellmcp.json").write_text(json.dumps({
    "component": "shellmcp",
    "build_version": int("$BUILD_VERSION"),
    "build_ts": "$BUILD_TS",
    "git_commit": "$GIT_COMMIT",
    "platform": "linux",
    "arch": "x86_64",
    "artifact_type": "binary-runtime+source",
    "runtime_payload": ["shellmcp/dist/shellmcp", "cli", "agents/generic_stdio_mcp_relay", "client"],
    "source_payload": ["client/shellmcp.py", "client/shellmcp_pure.py", "client/shellmcp_linux.py", "client/gptadmin_security.py", "client/gptadmin_build_info.py"],
    "sha256": sha,
    "url": "/artifacts/shellmcp.tar.gz",
}, ensure_ascii=False, indent=2)+"\n")
PY
  echo "built: $ART_DIR/gptadmin-shellmcp.tar.gz"
else
  echo "WARN: shellmcp dir not found, skip gptadmin-shellmcp.tar.gz"
fi

# полезно увидеть размеры
ls -lh gptadmin*.tar.gz 2>/dev/null || true
popd >/dev/null


# ---------- Smoke tests ----------
wait_for_http() {
  # wait_for_http URL [timeout_seconds] [extra_curl_args...]
  local url="$1"; local timeout="${2:-20}"; shift 2 || true
  local attempt
  for ((attempt=1; attempt<=timeout; attempt++)); do
    # ВАЖНО: НЕ используем -f — нам достаточно ЛЮБОГО HTTP-ответа (даже 404/401),
    # чтобы понять, что сервер уже поднялся и отвечает.
    if curl -sS "$url" "$@" -o /dev/null; then
      echo "HTTP OK: $url (attempt $attempt/$timeout)"
      return 0
    fi
    sleep 1
  done
  echo "Timeout waiting for $url"
  return 1
}
wait_for_listen_port() {
  # wait_for_listen_port PORT [timeout_seconds]
  local port="$1"; local timeout="${2:-20}"
  local attempt line
  for ((attempt=1; attempt<=timeout; attempt++)); do
    line="$(ss -ltn "( sport = :$port )" 2>/dev/null | sed -n '2p' || true)"
    if [[ -n "$line" ]]; then
      echo "LISTEN OK: :$port (attempt $attempt/$timeout)"
      return 0
    fi
    sleep 1
  done
  echo "Timeout waiting for port :$port to listen"
  return 1
}


# Возвращает 0 если порт ЗАНЯТ, 1 если свободен (без падений при set -e)
is_port_busy() {
  local port="$1"
  local line out
  if command -v ss >/dev/null 2>&1; then
    line="$(ss -ltn "( sport = :$port )" 2>/dev/null | sed -n '2p' || true)"
    [[ -n "$line" ]]
  elif command -v lsof >/dev/null 2>&1; then
    out="$(lsof -nP -iTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
    [[ -n "$out" ]]
  else
    return 1  # не можем проверить — считаем свободным
  fi
}

# Выбирает первый свободный порт начиная с base.
pick_port_plus1() {
  local base="$1"
  local port
  for ((port=base; port<base+50; port++)); do
    if ! is_port_busy "$port"; then
      echo "$port"
      return 0
    fi
  done
  echo "ERROR: no free port in range $base..$((base+49))" >&2
  exit 1
}


if [[ "$SKIP_TESTS" != "1" ]]; then
  [[ -x "$SHELLMCP_DIST" ]] || { echo "Missing $SHELLMCP_DIST"; exit 1; }
  [[ -x "$HUB_DIST"   ]] || { echo "Missing $HUB_DIST";   exit 1; }

    step "Smoke test: shellmcp"
    : > "$SHELLMCP_RT_LOG"
    SHELLMCP_PORT="$(pick_port_plus1 25900)"
    echo "Using SHELLMCP_PORT=$SHELLMCP_PORT"
    SHELLMCP_TOKEN=testtoken HUB_URL='' SHELLMCP_PORT="$SHELLMCP_PORT" \
    "$SHELLMCP_DIST" >"$SHELLMCP_RT_LOG" 2>&1 &
    SHELLMCP_PID=$!
    wait_for_http "http://127.0.0.1:${SHELLMCP_PORT}/version" 25
    curl -sS -f "http://127.0.0.1:${SHELLMCP_PORT}/version" | grep -q build_version
    kill "$SHELLMCP_PID" || true
    SHELLMCP_PID=""

    step "Smoke test: gptadmin_hub"
    : > "$HUB_RT_LOG"
    HUB_PORT="$(pick_port_plus1 9001)"
    echo "Using HUB_PORT=$HUB_PORT"
    CTL_TOKEN=ctltest HUB_PORT="$HUB_PORT" \
    "$HUB_DIST" >"$HUB_RT_LOG" 2>&1 &
    HUB_PID=$!

    # 1) ждём старт порта
    wait_for_listen_port "$HUB_PORT" 25

    # 2) проверяем /version (публичный) и /servers (авторизованный)
    wait_for_http "http://127.0.0.1:${HUB_PORT}/version" 10
    curl -sS -f "http://127.0.0.1:${HUB_PORT}/version" | grep -q build_version
    curl -sS -f "http://127.0.0.1:${HUB_PORT}/servers" -H "Authorization: Bearer ctltest" > /dev/null

    kill "$HUB_PID" || true
    HUB_PID=""



else
  echo "Skip smoke tests (SKIP_TESTS=1)"
fi

step "DONE: Artifacts stored in $ART_DIR"
echo "Main log: $LOG"
echo "Runtime logs: $SHELLMCP_RT_LOG, $HUB_RT_LOG"
echo "Cache dir: $CACHE_DIR  (delete with CLEAN=1)"
