# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 37
BUILD_TS = "2026-05-31T13:35:00Z"
GIT_COMMIT = "7f9357a"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
