# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 23
BUILD_TS = "2026-05-23T00:13:09Z"
GIT_COMMIT = "ec92dd6"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
