# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 27
BUILD_TS = "2026-05-23T12:09:32Z"
GIT_COMMIT = "a11192d"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
